name: Run dotnet format manually

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Format Code
      run: dotnet format

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply dotnet format fixes" || echo "No changes to commit"
        git push