name: Build HunterPie

on:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
          persist-credentials: false

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@main

      - name: Restore packages
        run: msbuild -m /t:Restore

      - name: Build HunterPie
        run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.sha }}
          path: ./HunterPie/bin/${{ env.BUILD_CONFIGURATION }}/**/
